# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imuPage.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(952, 609)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(590)
        self.tableWidget.setColumnCount(13)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(16)
        self.tableWidget.verticalHeader().setMinimumSectionSize(16)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.widget = MyFigure_Imu(Dialog)
        self.widget.setObjectName("widget")
        self.tableWidget.raise_()
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_starttime = QtWidgets.QLabel(Dialog)
        self.label_starttime.setObjectName("label_starttime")
        self.horizontalLayout.addWidget(self.label_starttime)
        self.label_duration = QtWidgets.QLabel(Dialog)
        self.label_duration.setObjectName("label_duration")
        self.horizontalLayout.addWidget(self.label_duration)
        self.label_frameCount = QtWidgets.QLabel(Dialog)
        self.label_frameCount.setObjectName("label_frameCount")
        self.horizontalLayout.addWidget(self.label_frameCount)
        self.btn_reset = QtWidgets.QPushButton(Dialog)
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout.addWidget(self.btn_reset)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(1, 3)
        self.tableWidget.raise_()
        self.btn_reset.raise_()
        self.widget.raise_()

        self.retranslateUi(Dialog)
        self.btn_reset.clicked.connect(Dialog.BtnResetTime)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "frameID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "gyro_dx"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "gyro_dy"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "gyro_zx"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "acc_dx"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "acc_dy"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "acc_dz"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "gyro_tx"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "gyro_ty"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "gyro_tz"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "acc_tx"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Dialog", "acc_ty"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("Dialog", "acc_tz"))
        self.label_starttime.setText(_translate("Dialog", "端口启动时间："))
        self.label_duration.setText(_translate("Dialog", "运行时长："))
        self.label_frameCount.setText(_translate("Dialog", "接收数据总帧数"))
        self.btn_reset.setText(_translate("Dialog", "复位"))

from MyWidgets import MyFigure_Imu
